import 'keys.dart';

class English {
  static Map<String, String> get messages => {
        I18nKeys.APP_NAME: 'Weather App',
        I18nKeys.ENTER_CITY_NAME: 'Enter city/county name',
        I18nKeys.ERROR: 'Error',
        I18nKeys.SOMETHING_WENT_WRONG: 'Something went wrong',
        I18nKeys.MAPS: 'Maps',
        I18nKeys.SCREENSHOT_TEXT: 'When I looked at the sky, I thought of you :)',
        I18nKeys.SORRY: 'Sorry',
        
        I18nKeys.DATE: 'Date',
        I18nKeys.TIMEZONE: 'Timezone',
        I18nKeys.COUNTRY: 'Country',
        I18nKeys.REGION: 'Region',
        I18nKeys.WIND_DIRECTION: 'Wind Direction',
        I18nKeys.WIND_POWER: 'Wind Power',
        I18nKeys.HUMIDITY: 'Humidity',
        "N": "North",
        "NbE": "North by East",
        "NNE": "North-Northeast",
        "NEbN": "Northeast by North",
        "NE": "Northeast",
        "NEbE": "Northeast by East",
        "ENE": "East-Northeast",
        "EbN": "East by North",
        "E": "East",
        "EbS": "East by South",
        "ESE": "East-Southeast",
        "SEbE": "Southeast by East",
        "SE": "Southeast",
        "SEbS": "Southeast by South",
        "SSE": "South-Southeast",
        "SbE": "South by East",
        "S": "South",
        "SbW": "South by West",
        "SSW": "South-Southwest",
        "SWbS": "Southwest by South",
        "SW": "Southwest",
        "SWbW": "Southwest by West",
        "WSW": "West-Southwest",
        "WbS": "West by South",
        "W": "West",
        "WbN": "West by North",
        "WNW": "West-Northwest",
        "NWbW": "Northwest by West",
        "NW": "Northwest",
        "NWbN": "Northwest by North",
        "NNW": "North-Northwest",
        "NbW": "North by West"
      };
}
