import 'keys.dart';

class Turkish {
  static Map<String, String> get messages => {
        I18nKeys.APP_NAME: 'Hava Durumu',
        I18nKeys.ENTER_CITY_NAME: 'Şehir/İlçe ismi girin',
        I18nKeys.ERROR: 'Hata',
        I18nKeys.SOMETHING_WENT_WRONG: 'Bir şey ters gitti',
        I18nKeys.MAPS: 'Haritalar',
        I18nKeys.SCREENSHOT_TEXT: 'Gökyüzüne bakınca aklıma sen geldin :)',
        I18nKeys.SORRY: 'Üzgünüm',
        I18nKeys.STAR_REQUEST: '5 yıldız verirseniz çok seviniriz :)',
        "N": "Kuzey",
        "NbE": "Kuzey Doğu",
        "NNE": "Kuzey-Kuzeydoğu",
        "NEbN": "Kuzey tarafından kuzeydoğu",
        "NE": "Kuzeydoğu",
        "NEbE": "Doğu tarafından kuzeydoğu",
        "ENE": "Doğu-Kuzeydoğu",
        "EbN": "Kuzey tarafından Doğu",
        "E": "Doğu",
        "EbS": "Güney tarafından Doğu",
        "ESE": "Doğu-Güneydoğu",
        "SEbE": "Doğu tarafından Güneydoğu",
        "SE": "Güneydoğu",
        "SEbS": "Güney tarafından Güneydoğu",
        "SSE": "Güney-Güneydoğu",
        "SbE": "Doğu tarafından Güney",
        "S": "Güney",
        "SbW": "Batı tarafından Güney",
        "SSW": "Güney-Güneybatı",
        "SWbS": "Güney tarafından Güneybatı",
        "SW": "Güneybatı",
        "SWbW": "Batı tarafından Güneybatı",
        "WSW": "Batı-Güneybatı",
        "WbS": "Güney tarafından Batı",
        "W": "Batı",
        "WbN": "Kuzey tarafından Batı",
        "WNW": "Batı-Kuzeybatı",
        "NWbW": "Batı tarafından kuzeybatı",
        "NW": "Kuzey Batı",
        "NWbN": "Kuzeybatı tarafından Kuzey",
        "NNW": "Kuzey Kuzey Batı",
        "NbW": "Batı tarafından Kuzey"
      };
}
